// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://titbzqxvgqzkxcbuujbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdGJ6cXh2Z3F6a3hjYnV1amJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzOTAwNTQsImV4cCI6MjA0OTk2NjA1NH0.Cule_QbiQ5g0FYS1jQPBRlOYscHhYUR1pUDoEYxS000";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);